export const menus = [
  // CHICKEN
  {
    menu_aid: 1,
    menu_title: "2pc Chickenjoy",
    menu_category: "Chickenjoy",
    menu_price: "200",
    menu_image: "chicken-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 2,
    menu_title: "3pc Chickenjoy",
    menu_category: "Chickenjoy",
    menu_price: "270",
    menu_image: "chicken-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 3,
    menu_title: "2pc Large Fries w/ Bucket Chickenjoy",
    menu_category: "Chickenjoy",
    menu_price: "400",
    menu_image: "chicken-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 4,
    menu_title: "Spaghetti w/ Bucket Chickenjoy",
    menu_category: "Chickenjoy",
    menu_price: "350",
    menu_image: "chicken-4.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 5,
    menu_title: "Bucket Chicken w/ Fries",
    menu_category: "Chickenjoy",
    menu_price: "320",
    menu_image: "chicken-5.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 6,
    menu_title: "Bucket Chickenjoy",
    menu_category: "Chickenjoy",
    menu_price: "290",
    menu_image: "chicken-6.webp",
    menu_is_active: true,
  },

  // YUM BURGER
  {
    menu_aid: 7,
    menu_title: "Yum Burger",
    menu_category: "Yum Burger",
    menu_price: "60",
    menu_image: "burger-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 8,
    menu_title: "Yum Burger w/ Fries",
    menu_category: "Yum Burger",
    menu_price: "79",
    menu_image: "burger-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 9,
    menu_title: "Cheese Burger",
    menu_category: "Yum Burger",
    menu_price: "89",
    menu_image: "burger-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 10,
    menu_title: "Yum Burger w/ Fries",
    menu_category: "Yum Burger",
    menu_price: "49",
    menu_image: "burger-4.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 11,
    menu_title: "Large Burger",
    menu_category: "Yum Burger",
    menu_price: "129",
    menu_image: "burger-5.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 12,
    menu_title: "Yum Burger w/ Fries",
    menu_category: "Yum Burger",
    menu_price: "79",
    menu_image: "burger-6.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 13,
    menu_title: "Double Cheese Burger",
    menu_category: "Yum Burger",
    menu_price: "200",
    menu_image: "burger-7.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 14,
    menu_title: "Double Cheese Burger w/ Fries",
    menu_category: "Yum Burger",
    menu_price: "250",
    menu_image: "burger-8.webp",
    menu_is_active: true,
  },

  // VALUE MEALS
  {
    menu_aid: 15,
    menu_title: "Chicken Burger Peach Mango w/ Fries Drinks",
    menu_category: "Value Meal",
    menu_price: "388",
    menu_image: "value-meal-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 16,
    menu_title: "4 Chicken Burger",
    menu_category: "Value Meal",
    menu_price: "400",
    menu_image: "value-meal-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 17,
    menu_title: "2pc Chickenjoy w/ Peach Mango & Coke",
    menu_category: "Value Meal",
    menu_price: "250",
    menu_image: "value-meal-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 18,
    menu_title: "3pcs Peach Mango & Bucket Meal",
    menu_category: "Value Meal",
    menu_price: "550",
    menu_image: "value-meal-4.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 19,
    menu_title: "2 ChickenBurger & 2LargeFries w/ Coke",
    menu_category: "Value Meal",
    menu_price: "250",
    menu_image: "value-meal-5.webp",
    menu_is_active: true,
  },

  // SIDES
  {
    menu_aid: 20,
    menu_title: "Regular Fries",
    menu_category: "Sides",
    menu_price: "150",
    menu_image: "sides-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 21,
    menu_title: "Mush Potato",
    menu_category: "Sides",
    menu_price: "30",
    menu_image: "sides-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 22,
    menu_title: "Rice",
    menu_category: "Sides",
    menu_price: "30",
    menu_image: "sides-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 23,
    menu_title: "Fried Rice",
    menu_category: "Sides",
    menu_price: "32",
    menu_image: "sides-4.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 24,
    menu_title: "Small Spaghetti",
    menu_category: "Sides",
    menu_price: "25",
    menu_image: "sides-5.webp",
    menu_is_active: true,
  },

  // PALABOK
  {
    menu_aid: 25,
    menu_title: "Palabok",
    menu_category: "Palabok",
    menu_price: "90",
    menu_image: "palabok-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 26,
    menu_title: "Palabok w/ Coke",
    menu_category: "Palabok",
    menu_price: "190",
    menu_image: "palabok-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 27,
    menu_title: "Family Palabok",
    menu_category: "Palabok",
    menu_price: "400",
    menu_image: "palabok-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 28,
    menu_title: "Family Palabok & Bucket Meal 3pc Peach Mango w/ Drinks",
    menu_category: "Palabok",
    menu_price: "1000",
    menu_image: "palabok-4.webp",
    menu_is_active: true,
  },

  // BURGER STEAK
  {
    menu_aid: 29,
    menu_title: "Steak",
    menu_category: "Burger Steak",
    menu_price: "89",
    menu_image: "steak-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 30,
    menu_title: "Family Steak",
    menu_category: "Burger Steak",
    menu_price: "380",
    menu_image: "steak-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 31,
    menu_title: "Family Steak & Bucket Meal w/ 3pcs Peach Mango",
    menu_category: "Burger Steak",
    menu_price: "790",
    menu_image: "steak-3.webp",
    menu_is_active: true,
  },

  // SPAGHETTI
  {
    menu_aid: 32,
    menu_title: "Spaghetti",
    menu_category: "Spaghetti",
    menu_price: "90",
    menu_image: "spag-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 33,
    menu_title: "Spaghetti w/ Chicken",
    menu_category: "Spaghetti",
    menu_price: "120",
    menu_image: "spag-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 34,
    menu_title: "Family Spaghetti",
    menu_category: "Spaghetti",
    menu_price: "350",
    menu_image: "spag-3.webp",
    menu_is_active: true,
  },

  // DESSERTS
  {
    menu_aid: 35,
    menu_title: "2pc Peach Mango Pie",
    menu_category: "Desserts",
    menu_price: "90",
    menu_image: "dessert-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 36,
    menu_title: "2pc Ube Mango",
    menu_category: "Desserts",
    menu_price: "90",
    menu_image: "dessert-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 37,
    menu_title: "5pc Peach Mango Pie",
    menu_category: "Desserts",
    menu_price: "5000",
    menu_image: "dessert-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 38,
    menu_title: "Lemon Juice",
    menu_category: "Desserts",
    menu_price: "60",
    menu_image: "dessert-4.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 39,
    menu_title: "Large Coke",
    menu_category: "Desserts",
    menu_price: "35",
    menu_image: "dessert-5.webp",
    menu_is_active: true,
  },
];
  